coincap_rate_api:
  outputs:
    dev:
      dbname: coincap_dwh
      host: postgres_db
      pass: coincap_password
      port: 5432
      schema: coincap_stg
      threads: 1
      type: postgres
      user: coincap_user
  target: dev
test_project:
  outputs:
    dev:
      dbname: postgres
      host: postgres_db
      pass: postgres
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev