coincap_rate_api:
  outputs:
    prod:
      dbname: coincap_dwh
      host: host.docker.internal
      pass: "{{ env_var('DWH_STG_PASSWORD') }}"
      port: 5432
      schema: coincap_prod
      threads: 1
      type: postgres
      user: coincap_user
  target: prod
test_project:
  outputs:
    dev:
      dbname: postgres
      host: postgres_db
      pass: postgres
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev