test_project:
  outputs:
    dev:
      dbname: postgres
      host: postgres_db
      pass: postgres
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev