id: run-geojson-script
namespace: coincap.grafana
tasks:
  - id: run-geojson-script
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - 'python /app/storage/coincap/grafana/_files/test.py'

triggers:
  - id: schedule_rate_geojson_run
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/5 * * * *"