id: consume-kafka-messages
namespace: coincap.api_flows
tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "{{ trigger.value }}"
  
triggers:
  - id: realtime_trigger
    type: io.kestra.plugin.kafka.RealtimeTrigger
    topic: test-topic
    properties:
      bootstrap.servers: broker:29092
    serdeProperties:
      valueDeserializer: STRING
    groupId: kestraConsumer