id: rate_api_archive
namespace: coincap.archive

tasks:
  - id: run_populate_rate_archive
    type: io.kestra.plugin.jdbc.postgresql.Query
    url: jdbc:postgresql://host.docker.internal:5432/coincap_dwh
    username: coincap_user
    password: coincap_password
    sql: |
      -- Insert archived data into the archive table
      INSERT INTO coincap_stg.rates_api_raw_archive
      SELECT id, symbol, rateUsd, source, event_timestamp
      FROM coincap_stg.rates_api_raw
      WHERE event_timestamp < CURRENT_TIMESTAMP - INTERVAL '10 minutes';
    fetchType: NONE

  - id: run_delete_rate_data
    type: io.kestra.plugin.jdbc.postgresql.Query
    url: jdbc:postgresql://host.docker.internal:5432/coincap_dwh
    username: coincap_user
    password: coincap_password
    sql: |
      -- Delete archived data from the original table
      DELETE FROM coincap_stg.rates_api_raw
      WHERE event_timestamp < CURRENT_TIMESTAMP - INTERVAL '10 minutes';
    fetchType: NONE


triggers:
  - id: schedule_rate_archive_run
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"