{
 "title": "btc",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Ethereum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH top_rates AS (\n    SELECT \n        rate_sr_key,\n        ROW_NUMBER() OVER (ORDER BY MAX(CAST(rateusd AS FLOAT)) DESC) AS row_num\t\t\n    FROM coincap_prod.fact_rates\n    GROUP BY rate_sr_key\n    ORDER BY MAX(CAST(rateusd AS FLOAT)) DESC\n    LIMIT 5\n)\nSELECT \n    d.id,\n    AVG(CAST(f.rateusd AS FLOAT)) AS \"Average Value\",\n    DATE_TRUNC('minute', f.event_timestamp) AS event_timestamp_minute\nFROM coincap_prod.fact_rates f\nLEFT JOIN coincap_prod.dim_rates d \n    ON f.rate_sr_key = d.rate_sr_key  \nLEFT JOIN top_rates t \n    ON f.rate_sr_key = t.rate_sr_key  \nWHERE t.row_num = 5\nGROUP BY event_timestamp_minute, d.id \nORDER BY event_timestamp_minute;\n"
    }
   ]
  },
  {
   "title": "Bitcoin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH top_rates AS (\n    SELECT \n        rate_sr_key,\n        ROW_NUMBER() OVER (ORDER BY MAX(CAST(rateusd AS FLOAT)) DESC) AS row_num\t\t\n    FROM coincap_prod.fact_rates\n    GROUP BY rate_sr_key\n    ORDER BY MAX(CAST(rateusd AS FLOAT)) DESC\n    LIMIT 5\n)\nSELECT \n    d.id,\n    AVG(CAST(f.rateusd AS FLOAT)) AS \"Average Value\",\n    DATE_TRUNC('minute', f.event_timestamp) AS event_timestamp_minute\nFROM coincap_prod.fact_rates f\nLEFT JOIN coincap_prod.dim_rates d \n    ON f.rate_sr_key = d.rate_sr_key  \nLEFT JOIN top_rates t \n    ON f.rate_sr_key = t.rate_sr_key  \nWHERE t.row_num = 1\nGROUP BY event_timestamp_minute, d.id \nORDER BY event_timestamp_minute;\n"
    }
   ]
  },
  {
   "title": "wrapped-bitcoin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH top_rates AS (\n    SELECT \n        rate_sr_key,\n        ROW_NUMBER() OVER (ORDER BY MAX(CAST(rateusd AS FLOAT)) DESC) AS row_num\t\t\n    FROM coincap_prod.fact_rates\n    GROUP BY rate_sr_key\n    ORDER BY MAX(CAST(rateusd AS FLOAT)) DESC\n    LIMIT 5\n)\nSELECT \n    d.id,\n    AVG(CAST(f.rateusd AS FLOAT)) AS \"Average Value\",\n    DATE_TRUNC('minute', f.event_timestamp) AS event_timestamp_minute\nFROM coincap_prod.fact_rates f\nLEFT JOIN coincap_prod.dim_rates d \n    ON f.rate_sr_key = d.rate_sr_key  \nLEFT JOIN top_rates t \n    ON f.rate_sr_key = t.rate_sr_key  \nWHERE t.row_num = 2\nGROUP BY event_timestamp_minute, d.id \nORDER BY event_timestamp_minute;\n"
    }
   ]
  },
  {
   "title": "gold-ounce",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH top_rates AS (\n    SELECT \n        rate_sr_key,\n        ROW_NUMBER() OVER (ORDER BY MAX(CAST(rateusd AS FLOAT)) DESC) AS row_num\t\t\n    FROM coincap_prod.fact_rates\n    GROUP BY rate_sr_key\n    ORDER BY MAX(CAST(rateusd AS FLOAT)) DESC\n    LIMIT 5\n)\nSELECT \n    d.id,\n    AVG(CAST(f.rateusd AS FLOAT)) AS \"Average Value\",\n    DATE_TRUNC('minute', f.event_timestamp) AS event_timestamp_minute\nFROM coincap_prod.fact_rates f\nLEFT JOIN coincap_prod.dim_rates d \n    ON f.rate_sr_key = d.rate_sr_key  \nLEFT JOIN top_rates t \n    ON f.rate_sr_key = t.rate_sr_key  \nWHERE t.row_num = 4\nGROUP BY event_timestamp_minute, d.id \nORDER BY event_timestamp_minute;\n"
    }
   ]
  }
 ]
}