{
 "title": "Live Crypto Rates",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "crypto_1",
    "label": "crypto_1",
    "query": "WITH top_rates AS (\n    SELECT \n        f.currency_sr_key ,\n        ROW_NUMBER() OVER (ORDER BY MAX(CURRENNCY_RATE_IN_USD) DESC) AS row_num\t\t\n    FROM coincap_prod.fact_currency_rate f\n    where currency_sr_key in (select currency_sr_key from\n                         coincap_prod.dim_currency_rate  dr \n                         where currency_type = 'crypto')\n    GROUP BY currency_sr_key\n    ORDER BY MAX(CURRENNCY_RATE_IN_USD) DESC\n    LIMIT 5\n)\nSELECT UPPER(d.currency_id) \nFROM coincap_prod.dim_currency_rate d\ninner JOIN top_rates t \n    ON d.currency_sr_key = t.currency_sr_key  \nWHERE t.row_num = 1;"
   },
   {
    "name": "crypto_2",
    "label": "crypto_2",
    "query": "WITH top_rates AS (\n    SELECT \n        f.currency_sr_key ,\n        ROW_NUMBER() OVER (ORDER BY MAX(CURRENNCY_RATE_IN_USD) DESC) AS row_num\t\t\n    FROM coincap_prod.fact_currency_rate f\n    where currency_sr_key in (select currency_sr_key from\n                         coincap_prod.dim_currency_rate  dr \n                         where currency_type = 'crypto')\n    GROUP BY currency_sr_key\n    ORDER BY MAX(CURRENNCY_RATE_IN_USD) DESC\n    LIMIT 5\n)\nSELECT UPPER(d.currency_id) \nFROM coincap_prod.dim_currency_rate d\ninner JOIN top_rates t \n    ON d.currency_sr_key = t.currency_sr_key  \nWHERE t.row_num = 2;"
   },
   {
    "name": "crypto_3",
    "label": "crypto_3",
    "query": "WITH top_rates AS (\n    SELECT \n        f.currency_sr_key ,\n        ROW_NUMBER() OVER (ORDER BY MAX(CURRENNCY_RATE_IN_USD) DESC) AS row_num\t\t\n    FROM coincap_prod.fact_currency_rate f\n    where currency_sr_key in (select currency_sr_key from\n                         coincap_prod.dim_currency_rate  dr \n                         where currency_type = 'crypto')\n    GROUP BY currency_sr_key\n    ORDER BY MAX(CURRENNCY_RATE_IN_USD) DESC\n    LIMIT 5\n)\nSELECT UPPER(d.currency_id) \nFROM coincap_prod.dim_currency_rate d\ninner JOIN top_rates t \n    ON d.currency_sr_key = t.currency_sr_key  \nWHERE t.row_num = 3;"
   },
   {
    "name": "crypto_4",
    "label": "crypto_4",
    "query": "WITH top_rates AS (\n    SELECT \n        f.currency_sr_key ,\n        ROW_NUMBER() OVER (ORDER BY MAX(CURRENNCY_RATE_IN_USD) DESC) AS row_num\t\t\n    FROM coincap_prod.fact_currency_rate f\n    where currency_sr_key in (select currency_sr_key from\n                         coincap_prod.dim_currency_rate  dr \n                         where currency_type = 'crypto')\n    GROUP BY currency_sr_key\n    ORDER BY MAX(CURRENNCY_RATE_IN_USD) DESC\n    LIMIT 5\n)\nSELECT UPPER(d.currency_id) \nFROM coincap_prod.dim_currency_rate d\ninner JOIN top_rates t \n    ON d.currency_sr_key = t.currency_sr_key  \nWHERE t.row_num = 4;"
   },
   {
    "name": "crypto_any",
    "label": "Select Crypto ",
    "query": "SELECT UPPER(d.currency_id) \nFROM coincap_prod.dim_currency_rate   d\nwhere d.currency_type='crypto'\norder by d.currency_id "
   }
  ]
 },
 "panels": [
  {
   "title": "${crypto_any}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    d.CURRENCY_id,\n    AVG(f.currenncy_rate_in_usd) AS \"Average Value\",\n    DATE_TRUNC('minute', f.event_timestamp) AS event_timestamp_minute\nFROM coincap_prod.fact_currency_rate  f\nINNER JOIN coincap_prod.dim_currency_rate  d \n    ON f.currency_sr_key  = d.currency_sr_key   \nWHERE UPPER(d.CURRENCY_id) = '${crypto_any}' \nGROUP BY event_timestamp_minute, d.CURRENCY_id \nORDER BY event_timestamp_minute;\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 }, "options": { "content": "# Top 4 Cryptocurrencies" } },
  {
   "title": "${crypto_1}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH top_rates AS (\n    SELECT \n        CURRENCY_SR_KEY,\n        ROW_NUMBER() OVER (ORDER BY MAX(currenncy_rate_in_usd) DESC) AS row_num\t\t\n    FROM coincap_prod.fact_currency_rate\n    where CURRENCY_SR_KEY  in (select CURRENCY_SR_KEY \n    \t\t\t\t\t   from coincap_prod.dim_currency_rate dr \n    \t\t\t\t\t   where dr.currency_type  = 'crypto'\n    \t\t\t\t\t   )\n    GROUP BY CURRENCY_SR_KEY\n    ORDER BY MAX(currenncy_rate_in_usd) DESC\n    LIMIT 5\n)\nSELECT \n    d.currency_id,\n    AVG(f.currenncy_rate_in_usd) AS \"Average Value\",\n    DATE_TRUNC('minute', f.event_timestamp) AS event_timestamp_minute\nFROM coincap_prod.fact_currency_rate   f\nINNER JOIN top_rates t \n    ON f.CURRENCY_SR_KEY = t.CURRENCY_SR_KEY  \nINNER JOIN coincap_prod.dim_currency_rate d \n    ON f.CURRENCY_SR_KEY = d.CURRENCY_SR_KEY  \nWHERE t.row_num = 1\nGROUP BY event_timestamp_minute, d.currency_id \nORDER BY event_timestamp_minute;\n"
    }
   ]
  },
  {
   "title": "${crypto_2}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH top_rates AS (\n    SELECT \n        CURRENCY_SR_KEY,\n        ROW_NUMBER() OVER (ORDER BY MAX(currenncy_rate_in_usd) DESC) AS row_num\t\t\n    FROM coincap_prod.fact_currency_rate\n    where CURRENCY_SR_KEY  in (select CURRENCY_SR_KEY \n    \t\t\t\t\t   from coincap_prod.dim_currency_rate dr \n    \t\t\t\t\t   where dr.currency_type  = 'crypto'\n    \t\t\t\t\t   )\n    GROUP BY CURRENCY_SR_KEY\n    ORDER BY MAX(currenncy_rate_in_usd) DESC\n    LIMIT 5\n)\nSELECT \n    d.currency_id,\n    AVG(f.currenncy_rate_in_usd) AS \"Average Value\",\n    DATE_TRUNC('minute', f.event_timestamp) AS event_timestamp_minute\nFROM coincap_prod.fact_currency_rate   f\nINNER JOIN top_rates t \n    ON f.CURRENCY_SR_KEY = t.CURRENCY_SR_KEY  \nINNER JOIN coincap_prod.dim_currency_rate d \n    ON f.CURRENCY_SR_KEY = d.CURRENCY_SR_KEY  \nWHERE t.row_num = 2\nGROUP BY event_timestamp_minute, d.currency_id \nORDER BY event_timestamp_minute;\n"
    }
   ]
  },
  {
   "title": "${crypto_3}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH top_rates AS (\n    SELECT \n        CURRENCY_SR_KEY,\n        ROW_NUMBER() OVER (ORDER BY MAX(currenncy_rate_in_usd) DESC) AS row_num\t\t\n    FROM coincap_prod.fact_currency_rate\n    where CURRENCY_SR_KEY  in (select CURRENCY_SR_KEY \n    \t\t\t\t\t   from coincap_prod.dim_currency_rate dr \n    \t\t\t\t\t   where dr.currency_type  = 'crypto'\n    \t\t\t\t\t   )\n    GROUP BY CURRENCY_SR_KEY\n    ORDER BY MAX(currenncy_rate_in_usd) DESC\n    LIMIT 5\n)\nSELECT \n    d.currency_id,\n    AVG(f.currenncy_rate_in_usd) AS \"Average Value\",\n    DATE_TRUNC('minute', f.event_timestamp) AS event_timestamp_minute\nFROM coincap_prod.fact_currency_rate   f\nINNER JOIN top_rates t \n    ON f.CURRENCY_SR_KEY = t.CURRENCY_SR_KEY  \nINNER JOIN coincap_prod.dim_currency_rate d \n    ON f.CURRENCY_SR_KEY = d.CURRENCY_SR_KEY  \nWHERE t.row_num = 3\nGROUP BY event_timestamp_minute, d.currency_id \nORDER BY event_timestamp_minute;\n"
    }
   ]
  },
  {
   "title": "${crypto_4}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH top_rates AS (\n    SELECT \n        CURRENCY_SR_KEY,\n        ROW_NUMBER() OVER (ORDER BY MAX(currenncy_rate_in_usd) DESC) AS row_num\t\t\n    FROM coincap_prod.fact_currency_rate\n    where CURRENCY_SR_KEY  in (select CURRENCY_SR_KEY \n    \t\t\t\t\t   from coincap_prod.dim_currency_rate dr \n    \t\t\t\t\t   where dr.currency_type  = 'crypto'\n    \t\t\t\t\t   )\n    GROUP BY CURRENCY_SR_KEY\n    ORDER BY MAX(currenncy_rate_in_usd) DESC\n    LIMIT 5\n)\nSELECT \n    d.currency_id,\n    AVG(f.currenncy_rate_in_usd) AS \"Average Value\",\n    DATE_TRUNC('minute', f.event_timestamp) AS event_timestamp_minute\nFROM coincap_prod.fact_currency_rate   f\nINNER JOIN top_rates t \n    ON f.CURRENCY_SR_KEY = t.CURRENCY_SR_KEY  \nINNER JOIN coincap_prod.dim_currency_rate d \n    ON f.CURRENCY_SR_KEY = d.CURRENCY_SR_KEY  \nWHERE t.row_num = 4\nGROUP BY event_timestamp_minute, d.currency_id \nORDER BY event_timestamp_minute;\n"
    }
   ]
  }
 ]
}