\getenv KESTRA_DB_USER KESTRA_DB_USER
\getenv KESTRA_DB_PASSWORD KESTRA_DB_PASSWORD

\echo KESTRA_DB_USER is :KESTRA_DB_USER
\echo KESTRA_DB_PASSWORD is :KESTRA_DB_PASSWORD


CREATE DATABASE kestra_db;

\c kestra_db
-- Create a user for Airflow
CREATE USER :KESTRA_DB_USER WITH PASSWORD :'KESTRA_DB_PASSWORD';


GRANT ALL PRIVILEGES ON DATABASE kestra_db TO :KESTRA_DB_USER;

-- Grant usage and privileges on the schema
GRANT ALL PRIVILEGES ON SCHEMA public TO :KESTRA_DB_USER;